# Maven
trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: PowerShell@1
  inputs:
    targetType: 'inline'
    script: '# Write your powershell commands here.
      New-Item -Type Directory -Force "${HOME}/.m2"
      Copy-Item -Force "$(settingsxml.secureFilePath)" "${HOME}/.m2/settings.xml"
      Write-Host "Hello World"
      
      # Use the environment variables input below to pass secret variables to this script.'
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# Download Secure File
# Download a secure file to a temporary location on the build or release agent
- task: DownloadSecureFile@2
  inputs:
    secureFile: "$(settingsxml.secureFilePath)"
    
- task: Maven@3
  inputs:
    codeCoverageTool: "JaCoCo"
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
    reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
    failIfCoverageEmpty: true  
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'